GoogleCloudPlatform/gcp-service-broker

- CHANGELOG.md
- README.md
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/cloudsql/cloudsql_suite_test.go
- brokerapi/brokers/cloudsql/credentials_generator.go
- brokerapi/brokers/cloudsql/credentials_generator_test.go
- product/metadata/gcp-service-broker.yml
- tile.yml
- Generate username/password inside of the CloudSQLBroker
- Mark username/password as optional fields in tile
- Don't require a value for `details.Parameters` on bind
- Unit tested CloudSQLBroker.Bind for credentials generation
- Deployed broker, created a new cloudsql instance, bound to an app. Username/Password populated in `VCAP_SERVICES` env variable
Fixes #13
> CloudSQL username and password are generated if not provided on bind

- CHANGELOG.md
- README.md
- cmd/get_plan_info/get_plan_info.go
- db_service/setup_db.go
#139 - plan information so that ids can be copied to manifest.yml
> 139 - add command to dump current plan information

- CHANGELOG.md
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/catalog.go
- brokerapi/brokers/models/service_broker.go
- brokerapi/brokers/spanner/broker.go
- db_service/db_service_test.go
- docs/customization.md
- fakes/fake_env_vars.go
- integration_tests/async_integration_test.go
- integration_tests/integration_test.go
- manifest.yml
- utils/utils.go
- vendor/code.cloudfoundry.org/lager/json_redacter.go
- vendor/code.cloudfoundry.org/lager/json_redacter_test.go
- vendor/code.cloudfoundry.org/lager/redacting_writer_sink.go
- vendor/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
- vendor/github.com/onsi/ginkgo/integration/_fixtures/hanging_suite/hanging_suite_test.go
Also added service/plan validation via a new lib.
Separating this info out per service will allow easier enable/disable/config of services especially for tile users, and reduces code complexity.
> 157 - refactor service and plan env vars

- docs/use.md
This better reflects the format of the version that is expected, and shows the different default values for different instance types.
> Update version text for cloud sql instances

- brokerapi/brokers/account_managers/sql_account_manager.go
- integration_tests/async_integration_test.go
Waiting for the ssl certificate request to complete makes the bind operation for mysql 2nd generation instances consistently take longer than 60 seconds, which is the default timeout. I'm removing the wait for now and adding a longer sleep to the integration tests so they will still pass.
The ssl certificates are returned before the bind operation finishes, but the instance needs to be updated to use them, which takes 40-60 seconds. The request will continue to run in the background.
> Remove wait for ssl certificate request to finish

- brokerapi/brokers/account_managers/sql_account_manager.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/gcp_service_broker.go
- docs/use.md
- integration_tests/async_integration_test.go
For #135
Service accounts will be created when binding to a cloud sql instance. The fields necessary to use the proxying libraries will be returned. These fields are project id, region and private key data.
ssl certs will be generated optionally, based on the generate_ssl_certs parameter to bind.
> Create service account for binds to cloud sql instances

- brokerapi/brokers/account_managers/sql_account_manager.go
- brokerapi/brokers/cloudsql/broker.go
- docs/use.md
- examples/go/sb-test/README.md
- examples/go/sb-test/api.go
Adding certs to the connection uri that is returned in VCAP_SERVICES to applications on bind, and updated go test app to use the uri for connections instead of building it's own uri.
Spring cloud connectors would only connect if I added the `jdbc` in front of the url.
> Update postgres uri to enable using spring cloud connectors

- brokerapi/brokers/account_managers/sql_account_manager.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/config/broker_config.go
- brokerapi/brokers/models/service_broker.go
- cmd/root.go
- db_service/migrations.go
- docs/customization.md
- pkg/broker/registry.go
- tile.yml
- utils/utils.go
Make the broker reference services from the new registry.
Now custom configuration is pulled in exactly ONE place. This allows #51 to be fixed as a side-effect because now a user can set the following properties to disable services:
```
service:
google-cloudsql-mysql:
enabled: false
google-cloudsql-postgres:
enabled: false
```
and/or the following environment variables:
```
GSB_SERVICE_GOOGLE_PUBSUB_ENABLED=false
```
...or through the new tile form.
> Use New Registry

- brokerapi/brokers/account_managers/sql_account_manager.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/config/broker_config.go
- db_service/migrations.go
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- pkg/client/example-runner.go
- pkg/generator/forms.go
- pkg/generator/types.go
- utils/utils.go
Helps fix #157, #155 
We can now read plans from the environment/viper variable for a given broker and parse append them to the main catalog's plans. Plus, tests for the above.
This leads us down the path toward fixing #231
> add custom plan parsing

- db_service/migrations.go
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- utils/utils.go
- utils/utils_test.go
This re-implements code that was earlier deleted as part of #155.
The code was originally removed because there were plans to refactor the way operators would enter plans.
More code was removed as part of #167 and #164 which obscured that this wasn't fully completed until later in this development cycle.
The end result being:
- Operators can continue to use the same user-defined plans they were before 4.0
- Plans are now roughly checked for validity
- We have tests for the plans
- We don't delete the table of stored plans which operators might be relying on (if they tried to upgrade in place, all their database plans would have been lost) so they can use the export command even after an upgrade to get themselves back into a valid state
Fixes #147 along the way
> fix custom plan handling

- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/gcp_service_broker.go
- db_service/db_service.go
This was non user-configurable and would require quite a bit of work to get working in a meaningful way (per service plan) so just remove it for now.
> removed instance limit fixes #213

- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/account_managers/sql_account_manager.go
Fixes #72 these have been updated to be consistently incorrect with their convention so they don't accidentally change in the future.
The existing e2e tests will validate that the keys are correct so no new testing is needed.
> made JSON keys explicit for credentials

- brokerapi/brokers/account_managers/iam.go
- brokerapi/brokers/account_managers/iam_test.go
- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/account_managers/service_account_manager_test.go
- brokerapi/brokers/account_managers/set.go
- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/cloudsql/common-definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/stackdriver_debugger/broker.go
- brokerapi/brokers/stackdriver_trace/broker.go
- brokerapi/brokers/storage/definition.go
- docs/customization.md
- docs/use.md
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- pkg/generator/customization-md.go
- pkg/generator/forms.go
- tile.yml
Created a whitelist of roles per service that can ensure nobody can bind to them with roles outside of the list. Can be selectively disabled per-service. The whitelists include non-legacy curated roles that do not have admin access over instances of the service.
The solution of looking up the role so late isn't ideal, but the circle-y imports will be fixed when the client gets refactored as part of 4.2.
Example bad request and response for GCS:
```
$ ./gcp-service-broker client bind --instanceid gcswl --params '{"role":"ml.admin"}' --serviceid b9e4332e-b42b-4680-bda5-ea1506797474 --config ../minimal.yml --planid e1d11f65-da66-46ad-977c-6d56513baf43 --bindingid bgcswlbad2
{
"url": "http://user:pass@localhost:8000/v2/service_instances/gcswl/service_bindings/bgcswlbad2",
"http_method": …
```
> IAM Whitelist

- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/pubsub/broker.go
- cmd/client.go
- cmd/get_plan_info.go
- examples/go/sb-test/api.go
- integration_tests/async_integration_test.go
- pkg/broker/example.go
Part of #207 this fixes problems in our [go report card](https://goreportcard.com/report/github.com/GoogleCloudPlatform/gcp-service-broker).
Once this and #271 are in, we can also run gofmt for another part of #207.
> fix go_vet, ineffassign, and misspell errors

- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/config/broker_config.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/service_broker.go
- db_service/migrations.go
- integration_tests/async_integration_test.go
- integration_tests/integration_test.go
- utils/utils.go
- utils/utils_test.go
This is purely a refactor with no functionality changes expected.
- Added comments to the handler.
- Brought logging into line with the REST API (what is logged will match what is passed in the URL).
- Removed unnecessary GCPAsyncServiceBroker.
- Simplified and de-duplicated Project ID detection.
> Simplify API handler

- CHANGELOG.md
- brokerapi/brokers/bigquery/broker.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/spanner/broker.go
- brokerapi/brokers/storage/broker.go
- docs/billing.md
- utils/utils.go
- utils/utils_test.go
Related to #251. Add labels to services that support them indicating the organization ID, space ID and instance ID to better support billing.
> added label support for bigquery, cloudsql, spanner and gcs

- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/account_managers/sql_account_manager.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/db.go
- integration_tests/async_integration_test.go
- integration_tests/integration_test.go
Fixes #228. Rather than using `panic` as a flow-control device, use `error` instead.
This mostly affects tests, which I've updated and re-ran to validate.
> don't use panics as flow-control

- brokerapi/brokers/bigquery/definition.go
- docs/use.md
- pkg/broker/variables.go
- pkg/broker/variables_test.go
- pkg/generator/types.go
- pkg/validation/constraint_builder.go
- pkg/validation/constraint_builder_test.go
Start adding JSON Schema support to the broker. This commit tests the waters for the general approach.
After annotating the rest of the fields, we'll be able to push validation up into the broker to fail faster, have more complete documentation, and (possibly) expose the schemas like the OSB Spec recommends.
This work also opens up the way for improving/implementing:
* #243 - we'll be able to validate operator overrides
* #254 - existing brokers will behave the same way as the new ones
* #251 - we can now support more interesting types
* #250 - we can start mashing up variables earlier because tests are explicit
* #79 - we can generate these based on the schema for some forms
* #224 - these constraints will be explicit in the schema and not tested/accommodated for in multiple places
> Schema support

- CHANGELOG.md
- docs/customization.md
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- pkg/generator/forms.go
- tile.yml
Fixes part of #98. Bind overrides are still pending and will be added to the same form once bind moves over to using `varcontext`.
These overrides are explicitly added before the user values so they'll be overwritten by them. I considered overwriting the values on the actual list of plan variables, but decided against it because those are evaluated and I don't think we want to be giving that power to operators yet; especially when the plan variables are executed in a very specific order to ensure they all resolve correctly.
Later on, when user-defined plans become a thing operators can customize to their hearts' content, but KISS for now.
> add support for operator overloading of provision defaults

- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/modelsfakes/fake_service_broker_helper.go
- brokerapi/brokers/models/service_broker.go
Add state polling to the BrokerHelper explicitly to be called after LastOperation succeeds. This does three things:
* Removes an additional piece of lifecycle management logic from each broker.
* Provides a standardized way we can upgrade state in the future when we need additional info to be gathered/stored. For example, re-fetching CloudSQL's status after an upgrade from v1 to v2.
* Gives us a path towards supporting updates.
Part of #250 and #305
> update service state after successful lastoperation

- brokerapi/brokers/api_service/broker.go
- brokerapi/brokers/bigquery/broker.go
- brokerapi/brokers/bigtable/broker.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/modelsfakes/fake_service_broker_helper.go
- brokerapi/brokers/models/service_broker.go
- brokerapi/brokers/pubsub/broker.go
- brokerapi/brokers/spanner/broker.go
- brokerapi/brokers/stackdriver_debugger/broker.go
- brokerapi/brokers/stackdriver_profiler/broker.go
- brokerapi/brokers/stackdriver_trace/broker.go
- brokerapi/brokers/storage/broker.go
- cmd/client.go
This moves handling of the operation ID for asynchronous deprovision calls into GCPServiceBroker.
The service broker is responsible for managing the state of the instance, platform, and database, allowing the ServiceBrokerHelper to be responsible for just calling the right APIs and formatting requests.
part of #250 and #305
> move handling of async deprovision to GCPServiceBroker

- brokerapi/brokers/cloudsql/common-definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- docs/custom-services.md
- pkg/varcontext/interpolation/eval_test.go
- pkg/varcontext/interpolation/funcs.go
I'd like your opinion(s) on this. I've gone and defined the schemas before changing the code for `broker.go` so you can compare the two.
I added the ability to do assertions in the broker variables. The set variables won't affect anything when run, but we do need them in order to maintain the same functionality we had before.
If the CloudSQL API behaves correctly, then we shouldn't need the assertion at all.
Based on all the transformation I've been doing, I wrote down guidelines for future services we (and others) build out.
There is a "breaking" change in this code when combined with the JSONSchema code. The hard drive constants we were provisioning with before weren't in any way valid, I suspect the CloudSQL API was seeing an invalid value and defaulting back to SSD, but if that's the …
> CloudSQL schemas

- .travis.yml
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/gcp_service_broker.go
Three changes I had to make when testing the JSONSchema stuff on provision. We should get Travis to run `go test ./...` on PRs as a sanity check.
* instanceID -> serviceId
* if raw params is nil, treat it as an empty map
* the defaults were causing regex checks to fail when the defaults were computed
> fixes for the JSONSchema checker that failed tests

- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/cloudsql/broker_test.go
- pkg/varcontext/builder_test.go
These tests are temporary and will ensure that the requests generated before and after the move to `varcontext` are the same.
> add tests for the oddities around CloudSQL before refactoring

- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/modelsfakes/fake_service_account_manager.go
- brokerapi/brokers/models/modelsfakes/fake_service_broker_helper.go
- brokerapi/brokers/models/service_broker.go
- brokerapi/brokers/stackdriver_debugger/broker.go
- brokerapi/brokers/stackdriver_profiler/broker.go
- brokerapi/brokers/stackdriver_trace/broker.go
Further #250 by simplifying the IAM account managers by making them return only connection info as a map rather than DB stuff they shouldn't care about.
This reduces a lot of the marshaling/unmarshaling of JSON we were doing internally and possible error cases that could raise.
> simplify BuildInstanceCredentials and Bind

- docs/custom-services.md
- pkg/broker/registry.go
- pkg/varcontext/builder.go
- pkg/varcontext/builder_test.go
This PR adds a concept of constants which aren't overridable by users or available in the output, they're simply there to be used if required.
These could include, for example, project ID, instance ID, service ID, default labels, instance information and mathematical constants.
This isn't the most elegant solution for a DSL, but a more complicated one would likely be overkill because this is the last major use-case for our internal "language" to make is suitable converting our existing variables over.
> added the concept of constants to varcontext which can't be overridden

- CHANGELOG.md
- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/cloudsql/sql_account_manager.go
- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/modelsfakes/fake_service_account_manager.go
- brokerapi/brokers/models/modelsfakes/fake_service_broker_helper.go
- brokerapi/brokers/models/service_broker.go
- brokerapi/brokers/stackdriver_debugger/broker.go
- brokerapi/brokers/stackdriver_profiler/broker.go
- brokerapi/brokers/stackdriver_trace/broker.go
Passes though provision instance details on the bind call. #250
With this done we'll be able to refactor to construct `varcontext`s on bind calls #304.
Also fixes a bug where datastore service accounts were getting the same name because the wrong variable was being passed for the default name.
> Bind instance passthrough

- docs/custom-services.md
- docs/customization.md
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- pkg/generator/forms.go
- tile.yml
Fixes #243, #98 allow operators to define defaults for bind calls that use varcontexts.
This PR adds a varcontext builder for binds similar to the way provision works. It also adds new environment variables and a form for configuring default overrides.
> create a varcontext builder for bind calls

- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/modelsfakes/fake_service_broker_helper.go
- brokerapi/brokers/models/service_broker.go
Add instance data to unbind. After this change, the system will do ALL state management (for the serve command) in the `gcp_service_broker`.
This is important to better reason about the state of the system at any one time. We can now define invariants the `gcp_service_broker` must hold to ensure we comply with OSB and avoid getting ourselves into weird failure states that require manual intervention.
> Add instance data to unbind

- CHANGELOG.md
- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/account_managers/service_account_manager_test.go
- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/common-definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/storage/definition.go
- docs/use.md
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- pkg/generator/forms.go
Move the role whitelist checks to use JSONSchema. This normalizes the way we do validation rather than special one-off checks. #304, #250
> validate roles using JSONSchema

- CHANGELOG.md
- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/cloudsql/common-definition.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/storage/definition.go
- docs/use.md
- pkg/client/example-runner.go
Move the `run-examples` command over to use JSON Schemas annotated on the output variables for validation.
This means we have improved documentation about expected values, examples in our docs, more robust tests against little mistakes where a type/existence check isn't enough and less custom code for validation.
The constraints listed are meant to be sanity checks rather than being exact. For example, the base64 regex used to validate service accounts matches both valid an invalid base64, but it's an approximation that's easy to explain, document, and works well as a sanity check. We want to validate that fields don't get transposed, deleted, overwritten, and have the general right shape and size.
~~Tests are still running on my machine, but I'm building this PR before going home to get …
> Move Example Tests to use JSONSchema

- brokerapi/brokers/bigquery/broker.go
- brokerapi/brokers/bigtable/broker.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/models/db.go
- brokerapi/brokers/pubsub/broker.go
- brokerapi/brokers/spanner/broker.go
- brokerapi/brokers/storage/broker.go
Changes the way we handle OtherDetails marshaling/unmarshalling so all the BrokerHelpers are consistent and don't need to know the back-end implementation.
> simplify other details handling

- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/broker_config.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/datastore/definition.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/stackdriver_debugger/definition.go
- brokerapi/brokers/stackdriver_profiler/definition.go
- brokerapi/brokers/stackdriver_trace/definition.go
- brokerapi/brokers/storage/definition.go
- pkg/broker/registry.go
- pkg/broker/service_definition.go
Move the services to having their own constructors that are defined in the service definition.
This moves us towards supporting multiple back-ends and gives a clear distinction between what the registry is and the GCPServiceBroker. Fixes #250
> Service constructors

- docs/custom-services.md
Make our lifecycle explicit for #336 and OKR.
This introduces new tags for managing the lifecycle of existing plugins and will help us be more explicit about the state of our plugins and provide us with a mechanism to communicate when services are being deprecated and what the broker is doing in response to it.
> initial work on lifecycle management doc

- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/datastore/definition.go
- docs/use.md
This adds namespaces for datastore that will be returned with the bind call so SpringCloudGcpDatastore can autoconfigure with the right namespace and we can achieve "multi-tenancy" on datastore.
fixes #291 
E2E tests are provided through the run-examples command.
> fix #291, add namespace for datastore

- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/firestore/broker.go
- brokerapi/brokers/firestore/definition.go
- brokerapi/brokers/gcp_service_broker.go
- docs/use.md
Add support for Firestore.
Two oddities about this service:
1) We're not allowing overriding the role whitelist because this service is new and won't have anyone relying on that.
2) Firestore uses the old datastore.* IAM roles, but that's called out in a comment.
From what I read Firestore does not support namespaces like Datastore did (instead, you do them yourself) so I left that property out and this is a purely IAM based service.
> added Firestore support

- pkg/providers/tf/definition.go
- pkg/providers/tf/job_runner.go
- pkg/providers/tf/provider.go
- pkg/providers/tf/wrapper/workspace.go
- pkg/providers/tf/wrapper/workspace_test.go
Adds support for a custom executor that lets you override the Terraform binary and paths used along with support for setting that up in the JobRunner.
Providers now accept a custom JobRunner rather than constructing it themselves. This will help when there are multiple versions of Terraform or plugin paths we want to load from.
> add optional executor to jobrunner

- CHANGELOG.md
- brokerapi/brokers/cloudsql/broker.go
- google-brokers/cloud-storage.yml
- pkg/broker/service_definition.go
- pkg/providers/tf/definition.go
- pkg/providers/tf/definition_test.go
- pkg/validation/struct_validator.go
- pkg/validation/struct_validator_test.go
- pkg/varcontext/builder.go
- pkg/varcontext/builder_test.go
I ran integration tests on this and the existing services still work.
This PR simplifies the way plans are defined and variables are computed to make brokerpaks more approachable.
The structure of plans now mimics that of the service so the fields are easier to explain and HIL values now support casting to JSONSchema approved types so we can more easily use things like Maps of auto-computed labels.
Together these should allow us to implement some non-trivial examples with these brokerpaks.
> cleanup definitions and add auto-casting

- utils/ziputil/zip.go
This cuts the size of a basic brokerpak to about 1/3rd.
> enable compression during zip creation

- brokerapi/brokers/storage/definition.go
Add the list permission to all examples in GCS that have storage.objectAdmin as the role. This fixes a discrepancy that Craig pointed out yesterday.
> add list to all GCS examples

- cmd/get_plan_info.go
- cmd/migrate.go
- cmd/serve.go
- cmd/show.go
- cmd/tf.go
- pkg/brokerpak/cmd.go
- pkg/brokerpak/fetch.go
- pkg/brokerpak/fetch_test.go
- pkg/providers/tf/job_runner.go
- pkg/providers/tf/wrapper/workspace.go
- utils/stream/stream.go
- utils/utils.go
Adds support for getting brokerpaks from Cloud Storage buckets using URLs like gsutil produces e.g. `gs://brokerpaks/my-pak.brokerpak`
Testing manually works just fine, but I can't seem to come up with a good way to write unit-tests for the fetcher without massively increasing the code size and complexity due to the way the GCS client library is structured. This is similar to the issue I faced when creating the cloud storage beat for Elastic.
If you have thoughts beyond testing this with our integration tests I'm happy to hear them.
> added support for fetching brokerpaks from GCS

- README.md
- cmd/pak.go
- cmd/tf.go
- google-brokers/google-redis.yml
- google-brokers/manifest.yml
- pkg/broker/variables.go
- pkg/providers/tf/wrapper/workspace.go
Fixes #210 
There are a few other enhancements with this commit:
* brokerpaks get validated on creation
* `tf list` now shows a duration if the operation is in progress so using it with `watch` is more friendly and can point to stalled processes.
* workspace returns an empty map rather than erroring if the tfstate file doesn't contain the contents of a workspace because Terraform prunes empty workspaces.
* brokervariables now get their JSONSchema type validated against the valid types.
> added memorystore for redis

- ci/tasks/go-test.yml
- tools/osdfgen/osdfgen_test.go
osdfgen should not be run during broker unit-tests because the dependencies are intentionally not in the vendor directory and will therefore fail the tests.
> remove osdfgen from unit tests

- pkg/providers/tf/job_runner.go
- pkg/providers/tf/wrapper/workspace.go
- pkg/providers/tf/wrapper/workspace_test.go
This PR moves environment variable overrides into a separate TerraformExecutor simplifying TerraformWorkspace and allowing environment variable overrides to be tested.
Integration tests with brokerpaks continue working with this change.
> moved environment variable configuration to a custom executor

- docs/brokerpak-specification.md
- pkg/brokerpak/cmd.go
- pkg/brokerpak/cmd_test.go
- pkg/brokerpak/config.go
- pkg/brokerpak/manifest.go
- pkg/brokerpak/registrar.go
- pkg/brokerpak/registrar_test.go
Fixes #387
This adds support for injecting custom environment variables into Terraform. We won't use this feature immediately, but it is something that's needed for people building paks that need credentials other than Google's and is our path towards multi-project support.
> added ability to set environment variables

- CHANGELOG.md
- brokerapi/brokers/cloudsql/broker_test.go
- brokerapi/brokers/cloudsql/postgres-definition.go
Moved all the Postgres machines to their equivalent custom machine types because PG only supports the standard machines if they have shared CPUs.
Added tests to make sure the values of the existing (and any new) custom machine types conform to the written spec.
> Fix for Postgres machine types

- docs/customization.md
- pkg/brokerpak/config.go
- pkg/brokerpak/config_test.go
- pkg/brokerpak/registrar.go
- pkg/brokerpak/registrar_test.go
- pkg/generator/forms.go
- tile.yml
Requesting one review, renamed plans -> services to accurately reflect what the field is being used for.
> naming mistake, plans -> services

- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/dataflow/definition.go
- brokerapi/brokers/datastore/definition.go
- brokerapi/brokers/dialogflow/definition.go
- brokerapi/brokers/firestore/definition.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/stackdriver/debugger_definition.go
- brokerapi/brokers/stackdriver/monitoring_definition.go
- brokerapi/brokers/stackdriver/profiler_definition.go
- brokerapi/brokers/stackdriver/trace_definition.go
- brokerapi/brokers/storage/definition.go
- pkg/broker/broker_test.go
- pkg/broker/catalog.go
- pkg/broker/registry.go
- pkg/broker/registry_test.go
- pkg/broker/service_definition.go
- pkg/generator/forms.go
- pkg/providers/builtin/registry_test.go
- tile.yml
Removing the functionality to enable/disable specific services. This was a vestigial artifact from the way services were originally defined in the tile as environment variable JSON blobs.
Builtin services now have a tag and can be enabled/disabled using the tag just like all the other tags.
> removed individual disable flags

- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/dataflow/definition.go
- brokerapi/brokers/datastore/definition.go
- brokerapi/brokers/dialogflow/definition.go
- brokerapi/brokers/firestore/definition.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/stackdriver/debugger_definition.go
- brokerapi/brokers/stackdriver/monitoring_definition.go
- brokerapi/brokers/stackdriver/profiler_definition.go
- brokerapi/brokers/stackdriver/trace_definition.go
- brokerapi/brokers/storage/definition.go
- pkg/providers/builtin/registry_test.go
Fixes #49. This PR marks all built-in services as non-free. It doesn't attempt to fetch pricing information, but we can at least indicate that services will incur cost.
An additional test is added for plan updating to be false for built-ins because we have no intention of opening that can of worms and risking data loss.
> mark built-in services as not-free

- db_service/db_service_test.go
- db_service/migrations.go
- db_service/migrations_test.go
This PR removes support from upgrading from database versions prior to V3. Instead, the user should upgrade from v2 (to v3)? to v4 which will allow the broker to correctly help them transition versions.
> Remove pre v3 upgrades

- pkg/broker/policy/policy.go
- pkg/broker/policy/policy_test.go
- utils/set.go
- utils/set_test.go
This PR adds a generic "rules engine" to the broker. Rather than being a full rules-engine, it behaves more like CSS. Rules are executed top to bottom and overwrite properties as they match.
The rules list also supports user-defined assertions which are executed when the rules are unmarshalled from their source. This lets the users enter rudimentary test cases that will be validated by the service on startup.
There are three immediate use-cases for this engine:
* Provision overrides
* Bind overrides
* Environment variable overrides (to add multi-project provisioning support)
Due to the service being extensible, provision and bind overrides can no longer be handled in a generic way through the forms.
User entered rules will look something like this for a fizzbuzz based example:
```json
{ …
```
> Cascading Policies

- cmd/serve.go
- pkg/broker/registry.go
- pkg/broker/service_definition.go
- pkg/generator/forms.go
- pkg/toggles/toggle.go
The form for toggling compatibility settings is now changed to a general purpose feature flags form simplifying it: #421 
@craigatgoogle I jinxed myself when I said: "I better get this right the first time."
> rename compatibility form to features

- CHANGELOG.md
- brokerapi/brokers/broker_config.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/gcp_service_broker.go
- cmd/client.go
- cmd/generate.go
- docs/upgrading.md
- pkg/broker/broker_test.go
- pkg/broker/registry.go
- pkg/broker/registry_test.go
- pkg/broker/service_config.go
- pkg/broker/service_config_test.go
- pkg/broker/service_definition.go
- pkg/brokerpak/cmd.go
- pkg/brokerpak/cmd_test.go
- pkg/brokerpak/registrar.go
- pkg/brokerpak/registrar_test.go
- pkg/client/example-runner.go
- pkg/generator/forms.go
- pkg/generator/types.go
- pkg/providers/builtin/cloudsql/broker_test.go
- pkg/providers/builtin/registry.go
- pkg/providers/builtin/registry_test.go
- pkg/server/docs.go
- pkg/server/docs_test.go
- utils/utils.go
- utils/utils_test.go
This is 1/2 of the full work to move the broker into using a general `GSB_SERVICE_CONFIG` environment variable and removes the following variables:
* `GSB_SERVICE_*_WHITELIST`
* `GSB_SERVICE_*_PROVISION_DEFAULTS`
* `GSB_SERVICE_*_BIND_DEFAULTS`
* `GSB_SERVICE_*_ENABLED`
* `*_CUSTOM_PLANS`
What's included:
* Created new types: `ServiceConfig`, `ServiceConfigMap` and 
* Refactored BrokerRegistry to be named ServiceRegistry and include the user-customization options.
What will be included in another PR:
* The tile form for the `GSB_SERVICE_CONFIG` field and user-facing documentation for it.
* The migration script that generates `GSB_SERVICE_CONFIG`.
Part of #420
> Service Configuration Changeup

- CHANGELOG.md
- cmd/pak.go
- pkg/broker/variables.go
- pkg/providers/tf/definition.go
- utils/version.go
- The `pak run-examples` sub-command now returns a non-zero status code on failure.
- JSONSchema validation no longer fails due to erroneous duplicate required fields.
- Brokerpaks no longer use incorrect templates due to an invalid pointer.
The intent is to merge this into v4.2.1, then release a hotfix from that branch before merging it back into master
> fixed brokerpak issues

- cmd/config.go
- pkg/broker/registry.go
- pkg/broker/registry_test.go
- pkg/broker/service_config.go
- pkg/config/migration/four-to-five.go
- pkg/config/migration/four-to-five_test.go
- pkg/config/migration/js.go
- pkg/config/migration/js_test.go
- pkg/config/migration/migration.go
- pkg/config/migration/migration_test.go
This includes code for the 4 to 5 tile and CLI migrations. As-of v5.0 all configuration for a service will be consolidated to a single environment variable `GSB_SERVICE_CONFIG`.
This variable is a map of service GUID -> service configurations. Each service configuration has a comment, a disabled flag, a list of custom plans, and provision and bind defaults. In total, this consolidates seven forms down to one.
The tile migration takes the following route:
* Whitelist keys are deleted because they're no longer used/supported.
* Custom plans get "collapsed" from something the tile uses internally into a flat JSON map of key->values like what happens when Opsman turns the tile into environment variables.
* Custom plans get formatted, meaning custom properties are put into a format that can be …
> 4-to-5 migration

- CHANGELOG.md
- pkg/brokerpak/cmd.go
- pkg/brokerpak/manifest.go
Fixes #430, #431
Pleasantly surprising, the existing test cases didn't need to be updated because they actually respected return values rather than hard-coding.
- Built Brokerpaks now have a name of `{name}-{version}.brokerpak` as defined by the manifest rather than the name of the parent directory.
- Services inside Brokerpaks now have a file name that includes their CLI friendly name to help differentiate them.
- The `pak build` command now includes progress logs.
> Brokerpak Quality of Life Improvements

- CHANGELOG.md
- brokerapi/brokers/gcp_service_broker.go
- docs/brokerpak-specification.md
- pkg/broker/broker_test.go
- pkg/broker/service_definition.go
- pkg/providers/tf/definition.go
- pkg/providers/tf/definition_test.go
Adds the ability to get values from the plan at binding time. This is going to be used by certain plugins that have noop provisions but do have bindings that need to be configured by operators. The motivating example is IAM, operators should be able to create custom plans that users can use to bind service accounts with various roles but provisioning is undefined on them.
This has three parts:
1. Add plan info to be available under the `request.plan_properties` variable in HIL.
2. Change the Brokerpak loader's definition to work with these variables if they're declared under the BindSettings YAML section via a shim. Previously, no service had needed this so they weren't included as part of the variable resolution lifecycle.
3. Update the tests for these and write a new test for the …
> added ability to get plan info from bind

- docs/brokerpak-specification.md
- pkg/varcontext/interpolation/eval_test.go
- pkg/varcontext/interpolation/funcs.go
This was preventing certain use-cases with labels in brokerpaks.
> added map flatten function for HIL

- CHANGELOG.md
- docs/brokerpak-specification.md
- docs/service-config.md
- docs/use.md
- pkg/broker/broker_test.go
- pkg/broker/catalog.go
- pkg/broker/service_config.go
- pkg/broker/service_definition.go
- pkg/generator/service-config-md.go
- pkg/generator/types.go
- pkg/providers/builtin/storage/definition.go
- pkg/providers/tf/definition.go
This allows operators to define plans that can override user provision and bind parameters.
This means more fine-grained control for operators that need complete control on their environment and more variables given to developers in all other environments.
This will also allow us as broker developers to build plans that target specific use-cases; for example in order to get an HA instance of Postgres you need a certain set of variables set in a specific way.
> add ability for operators to override user variables in plans

- CHANGELOG.md
- docs/billing.md
- utils/utils.go
- utils/utils_test.go
Part of #446, expanding supported labels so policies can be written against them for operators to change Terraform environment variables on the fly.
> added expanded label support

- cmd/pak.go
- pkg/brokerpak/cmd.go
This is useful for faster turnaround when developing brokerpaks.
> added flag to run only a single example for brokerpaks

- pkg/generator/types.go
The formatter expected all values to be strings but that's not actually the case for some of the values we want to format so this is now a generic value to enable formatting values like `true` and `42`.
> fixed formatting of some fields in the generated docs

- docs/customization.md
- pkg/brokerpak/config.go
- pkg/brokerpak/config_test.go
- pkg/brokerpak/registrar.go
- tile.yml
The broker will now check /usr/share/gcp-service-broker/builtin-brokerpaks
on startup if GSB_COMPATIBILITY_ENABLE_BUILTIN_BROKERPAKS is set.
This allows us to bundle brokerpaks with the Docker image so users don't
have to download and install builtin paks and/or they can extend with
custom paks.
>  Added ability to load brokerpaks from local FS

- CHANGELOG.md
- google-brokers/google-redis.yml
Because of the data resource 'default-network' it was needed to have a
default network even though one might not use it as "authorized_network".
When you're not having a 'default' network and you're trying to create a google-redis service with the following command, terraform fails with the appended error message.
```bash
$ cf create-service experimental-google-redis basic redis-01 -c '{"authorized_network":"<ANY_OTHER_THAN_DEFAULT>"}'
```
Error message:
```
data.google_compute_network.default-network: Refreshing state...
module.instance.data.google_compute_network.default-network: Refreshing state...
Error: Error applying plan:
1 error(s) occurred:
* module.instance.google_redis_instance.instance: Resource 'data.google_compute_network.default-network' not found for variable …
```
> Remove dependency for a default network

- pkg/providers/builtin/cloudsql/broker.go
- pkg/providers/builtin/cloudsql/broker_test.go
- pkg/providers/builtin/cloudsql/mysql-definition.go
- pkg/providers/builtin/cloudsql/sql_account_manager.go
Fixes #466
This PR changes the way deletes are done from just deleting the master MySQL instance and any failover replicas it has. Replicas must be deleted before the master.
One fun side-effect is that even after the replica is done deleting the core instance may remain blocked for some period of time (returning HTTP status code 409s for attempts to delete it) so we have to repeatedly try until we get an operation id back.
A new example exercises the failed functionality and integration tests should show that it works now. A new field was added to the request `failover_replica_suffix`, if set it will set `failover_replica_name` to be the the instance name + the suffix. This allows us to use the randomly generated instance ids with failovers.
> delete replicas if they exist, fixes #466

- .gitignore
- pkg/providers/builtin/redis/broker.go
- pkg/providers/builtin/redis/definition.go
- pkg/providers/builtin/registry.go
Add Redis as a built-in service with two service plans corresponding to the two service tiers:
- basic
- standard high availability
Users can also specify the Redis instance's
- authorized network
- capacity tier
- display name
- instance id
- location id
Service Broker outputs instance variables to client can connect to the Redis instance: 
- name
- host
- port
- redis version
- memorysize in GiB
Console output after creating an instance example with "Basic Tier" examples:
```
2019/06/21 12:08:18 Running Example: google-memorystore-redis/Basic Redis Configuration
2019/06/21 12:08:18 gcp-service-broker client provision --instanceid "ex1103823129" --planid "dd1923b6-ac26-4697-83d6-b3a0c05c2c94" --serviceid "3ea92b54-838c-4fe1-b75d-9bda513380aa" --params "{}"
2019/06/21 12:08:18 …
```
> Add support for Memorystore for Redis

- db_service/migrations.go
- db_service/models/historical_db.go
closes #468 
Currently the column request_detail in the table ProvisionDetails
is of type string, actually it's varchar(255), which is not enough
space to store JSON based configuration data for creating services.
@josephlewis42 please let me know if I missed something. I am new to service broker development and more than happy to get your feedback and advisory in order to move this thing forward!
> Migrate column request_detail to datatype text

- pkg/client/example-runner.go
- pkg/client/example-runner_test.go
This commit resolves #484 
Testing:
- Added example function for `GetAllCompleteServiceExamples` that serves as a sanity check to make sure the function runs error-free, and returns a non-nil array of `CompleteServiceExamples` given the builtin registry.
- Added unit tests to `GetExamplesForAService`, to make sure we could get valid `CompleteServiceExamples` given a `ServiceDefinition`
- Added unit tests for the logic in `FilterMatchingServiceExamples`
> Refactor RunExample to run self-contained examples

- cmd/serve.go
- pkg/server/examples.go
- pkg/server/examples_test.go
This commit partly resolves #492
>  Add new /examples endpoint that returns array of CompleteServiceExamples

- cmd/client.go
- pkg/brokerpak/cmd.go
- pkg/client/example-runner.go
- pkg/client/example-runner_test.go
- pkg/server/examples.go
- pkg/server/examples_test.go
This commit resolves #492 
This commit refactors the code in the client to fetch examples from the endpoint rather than from the `builtin.BuildtinBrokerRegistry`. The client command `run-examples` now connects to the server, gets the list of examples from the endpoint, and runs them. The `--example-name`, `--service-name`, and `--filename` flags should continue to work.
Changes include:
- Refactoring some functions from the `client` to `server` pkg (`GetAllCompleteServiceExamples()`, `ExampleGetAllCompleteServiceExamples()` to avoid a circular import dependency
- Re-orders some imports in alphabetical order
- Refactoring code in `brokerpak` pkg to use `GetAllCompleteServiceExamples()` with the pak registry
For testing:
- Ran unit tests in `pkg/client/example-runner_test.go` and …
> Refactor code in client to fetch examples from the server endpoint

- CHANGELOG.md
- docs/brokerpak-specification.md
- pkg/broker/broker_test.go
- pkg/broker/service_definition.go
- pkg/providers/tf/definition.go
- pkg/providers/tf/definition_test.go
Already submitted as #442 , just cherrypicking to master
Adds the ability to get values from the plan at binding time. This is going to be used by certain plugins that have noop provisions but do have bindings that need to be configured by operators. The motivating example is IAM, operators should be able to create custom plans that users can use to bind service accounts with various roles but provisioning is undefined on them.
This has three parts:
1. Add plan info to be available under the `request.plan_properties` variable in HIL.
2. Change the Brokerpak loader's definition to work with these variables if they're declared under the BindSettings YAML section via a shim. Previously, no service had needed this so they weren't included as part of the variable resolution lifecycle.
3. …
> cherrypick #442 to master

- db_service/vcap.go
When trying to deploy the service broker as a Pivotal tile or cloud foundry application it is likely to fail (at least while using the old way to provide database credentials).
CloudFoundry by default provides a `VCAP_SERVICES={}` environment variable.
See `system_env_json` [here](https://apidocs.cloudfoundry.org/230/apps/get_app_summary.html):
> environment_json for system variables, **contains vcap_services by default**, a hash containing key/value pairs of the names and information of the services associated with your app.
> Tolerate an empty json hash for VCAP_SERVICES

- CHANGELOG.md
- db_service/migrations.go
In a previous commit (#bf2000b) the datatype for the column request_details
in the table provision_request_details was changed to text. Unfortunately
this only works for fresh service broker installations as gorm does not
modify the column type for existing columns.
As of this gorm's ModifyColumn has to be used explicitly.
> Add migration to modify column type

- CHANGELOG.md
- pkg/providers/builtin/cloudsql/broker.go
- pkg/providers/builtin/cloudsql/sql_account_manager.go
@basiszwo and I found two issues when trying to unbind a CloudSQL service instance.
1. When using the CloudSQL Postgres, it is possible that there are database objects depending on the bind-user. So an unbind would fail with the following error:
```
error occurred:
* Error deleting user: googleapi: Error 400: Invalid request: Failed to delete user <USERID>.
Detail: pq: role "<USERID>" cannot be dropped because some objects depend on it.
```
Since the Unbind function is implemented with an error-accumulator, it would still execute the other steps (like deleting the Service Account) and fail afterwards.
This might lead to a state where the binding still exists, but the Service Account is deleted.
In that case, our developers aren't able to connect to the CloudSQL instance on their own …
> Fix cloudsql user deletion and error handling

- pkg/providers/builtin/account_managers/iam.go
- pkg/providers/builtin/account_managers/iam_test.go
- pkg/providers/builtin/account_managers/service_account_manager.go
This PR fixes #474.
The IAM policy won't automatically be cleaned up when deleting a service
account. It is necessary to manually remove the service account from all
its role memberships. Otherwise, all created role bindings will remain
existent in the policy, leading to many orphaned bindings.
*Since I'm relatively new to programming in golang:*
I had problems finding an easy solution on how to avoid the code duplication in the methods `revokeRolesFromAccount` and `grantRoleToAccount`.
I would appreciate any hint on how I could/should (or should not?) resolve this! 🙂
> Cleanup IAM policy when deleting a service account

- pkg/providers/builtin/storage/definition.go
**Description**
The regex for bucket name is different than this specified in docs. Using uppercase characters fails with
```
Warning  ProvisionCallFailed               113s (x10 over 10m)  service-catalog-controller-manager  Error provisioning ServiceInstance of ServiceClass (K8S: "nagduan/b9e4332e-b42b-4680-bda5-ea1506797474" ExternalName: "google-storage") at ClusterServiceBroker "hb-google-cloud-platform-service-broker-default-e2076-gcp-servi": Status: 500; ErrorMessage: <nil>; Description: Error creating new bucket: googleapi: Error 400: Invalid bucket name: 'sapteched_2019_BNC_AMBA', invalid; ResponseError: <nil>
```
Docs:
> Bucket names must contain only lowercase letters, numbers, dashes (-), underscores (_), and dots (.). Names containing dots require verification.
source: …
> Fix storage name regex

- .travis.yml
- docs/classes/google-memorystore-redis.md
- docs/classes/google-storage.md
- hack/verify-generated.sh
**Description**
Currently is easy to forget about executing gcp-broker generators. 
Current problems on the master are caused by those PRs:
- https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/544 - this is also my fault 🤦‍♂ 
- https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/535
The source was changed but docs are not updated. As a result, the master docs are inconsistent with the master binary and docker image.
Changes proposed in this pull request:
- Add  helper script for validating if GCP Service Broker generators were executed and results were committed
- Execute verify-generated.sh script on CI
- Introduce named stages for Travis. 
- **stage:** Test
- unit tests
- verify generated sources
- **stage:** build
- docker image build
- Update generated …
>  Add verify generated stage for travis jobs

- deployments/helm/gcp-service-broker/requirements.yaml
The repository value pointed to the old location for stable charts. I updated it to: https://charts.helm.sh/stable
> Update requirements.yaml to point to correct helm repo
