GoogleCloudPlatform/gcp-service-broker

- integration_tests/integration_test.go
- Generalized test
- Added new cases for pub sub, cloud storage
- Removed hard coded project id assert
- ran the tests
> Integration tests for PubSub, Cloud Storage

- integration_tests/integration_test.go
This change is based off of PR #69 which should be merged before accepting this one.
> Unique instance names for Integration Tests

- README.md
Fix spelling, capitalization, formatting, whitespace, etc. Each commit has more info.
To see a rendered preview, click on `View` in the diff.
> Various formatting and readability fixes for the README 

- ci/pipeline.yml
- ci/tasks/ship-tile.sh
- ci/tasks/ship-tile.yml
and separate out release-version from dev/test version
> Concourse updates to make build production tile manual

- integration_tests/integration_test.go
#126 
This is the first line of Go I've ever written, so don't hate me if this breaks everything.
> getting rid of equal nil

- CHANGELOG.md
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/gcp_service_broker.go
- db_service/db_service.go
- docs/customization.md
- fakes/fake_env_vars.go
- manifest.yml
> fixes #147 - require plans to have id set

- glide.lock
- glide.yaml
- vendor/cloud.google.com/go/README.md
- vendor/cloud.google.com/go/spanner/doc.go
- vendor/code.cloudfoundry.org/lager/json_redacter.go
- vendor/code.cloudfoundry.org/lager/json_redacter_test.go
- vendor/code.cloudfoundry.org/lager/redacting_writer_sink.go
- vendor/gopkg.in/validator.v2/.gitignore
- vendor/gopkg.in/validator.v2/.travis.yml
- vendor/gopkg.in/validator.v2/LICENSE
- vendor/gopkg.in/validator.v2/README.md
- vendor/gopkg.in/validator.v2/builtins.go
- vendor/gopkg.in/validator.v2/doc.go
- vendor/gopkg.in/validator.v2/examplevalidate_test.go
- vendor/gopkg.in/validator.v2/validator.go
- vendor/gopkg.in/validator.v2/validator_test.go
I think this is needed more than envconfig for validating services and plans.
> adding validator library

- tile.yml
> tile: fix spanner node description

- brokerapi/brokers/cloudsql/broker.go
Typo fix causing bad JDBC URIs to be returned from the CloudSQL broker.
> jbdc -> jdbc

- README.md
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/service_broker.go
- brokerapi/brokers/stackdriver_profiler/broker.go
- brokerapi/brokers/stackdriver_profiler/definition.go
- docs/customization.md
- docs/use.md
- tile.yml
Fixes #237 
It looks like there isn't an SVG named "profiler" so I'm using the standard Stackdriver one.
> added support for stackdriver profiler #237

- brokerapi/brokers/api_service/broker.go
- brokerapi/brokers/bigquery/broker.go
- brokerapi/brokers/bigtable/broker.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/config/broker_config.go
- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/models/catalog.go
- brokerapi/brokers/pubsub/broker.go
- brokerapi/brokers/spanner/broker.go
- brokerapi/brokers/stackdriver_debugger/broker.go
- brokerapi/brokers/stackdriver_profiler/broker.go
- brokerapi/brokers/stackdriver_trace/broker.go
- brokerapi/brokers/storage/broker.go
This doesn't fix all the missing strings across the application, but at least covers the brokers
> Fix and add godoc strings for the brokers

- brokerapi/brokers/account_managers/iam_test.go
- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/account_managers/set.go
- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/common-definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/datastore/definition.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/stackdriver_debugger/definition.go
- brokerapi/brokers/stackdriver_profiler/definition.go
- brokerapi/brokers/stackdriver_trace/definition.go
- brokerapi/brokers/storage/definition.go
- pkg/broker/broker_test.go
- pkg/generator/forms.go
Ran `gofmt -s` over the non-generated code to help resolve #207.
> gofmt code for #207

- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/api_service/definition.go
- brokerapi/brokers/bigquery/definition.go
- brokerapi/brokers/bigtable/definition.go
- brokerapi/brokers/cloudsql/common-definition.go
- brokerapi/brokers/cloudsql/mysql-definition.go
- brokerapi/brokers/cloudsql/postgres-definition.go
- brokerapi/brokers/datastore/definition.go
- brokerapi/brokers/pubsub/definition.go
- brokerapi/brokers/spanner/definition.go
- brokerapi/brokers/stackdriver_debugger/definition.go
- brokerapi/brokers/stackdriver_profiler/definition.go
- brokerapi/brokers/stackdriver_trace/definition.go
- brokerapi/brokers/storage/definition.go
- docs/customization.md
- docs/use.md
- pkg/generator/customization-md.go
- pkg/generator/forms.go
- pkg/generator/types.go
Normalized sentences in documentation. Fixes #259
> Normalize docs

- docs/use.md
- pkg/generator/types.go
@mattysweeps added those names and example commands based on the examples for each service to be more in-line with our docs.
> updated to include example commands, fixes #279

- brokerapi/brokers/account_managers/service_account_manager.go
- brokerapi/brokers/account_managers/sql_account_manager.go
- brokerapi/brokers/api_service/broker.go
- brokerapi/brokers/bigquery/broker.go
- brokerapi/brokers/bigtable/broker.go
- brokerapi/brokers/broker_base/broker_base.go
- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/cloudsql/broker.go
- brokerapi/brokers/datastore/broker.go
- brokerapi/brokers/gcp_service_broker.go
- brokerapi/brokers/models/modelsfakes/fake_account_manager.go
- brokerapi/brokers/models/modelsfakes/fake_service_account_manager.go
- brokerapi/brokers/models/modelsfakes/fake_service_broker_helper.go
- brokerapi/brokers/models/service_broker.go
- brokerapi/brokers/pubsub/broker.go
- brokerapi/brokers/spanner/broker.go
- brokerapi/brokers/stackdriver_debugger/broker.go
- brokerapi/brokers/stackdriver_profiler/broker.go
- brokerapi/brokers/stackdriver_trace/broker.go
- brokerapi/brokers/storage/broker.go
- db_service/dao.go
- db_service/dao_generator.go
- db_service/dao_test.go
- db_service/db_service.go
Working towards #250, pass context along with our requests.
> pushed down context usage

- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/config/broker_config.go
- brokerapi/brokers/gcp_service_broker.go
- cmd/serve.go
- docs/customization.md
- docs/use.md
- pkg/generator/forms.go
- tile.yml
* add feature flag for input validation
I tacked on the boolean to the `GCPServiceBroker` and `BrokerConfig` structs. I'm open to alternative designs, as I'm new to these woods.
Also regenerated all the things
> Validate bind input parameters

- CHANGELOG.md
- README.md
- brokerapi/brokers/dataflow/broker.go
- brokerapi/brokers/dataflow/definition.go
- brokerapi/brokers/gcp_service_broker.go
Dataflow is another API only service, testing is achieved through the e2e tests. Closes #8
> Added support for Dataflow

- CHANGELOG.md
> add note about CVE

- cmd/client.go
- pkg/client/client.go
- pkg/client/example-runner.go
don't use the default registry anymore for the client because we'll be adding support for targeted registries soon.
> make client use a specified registry

- cmd/generate.go
- pkg/generator/types.go
another prerequisite for the brokerpak PR
> moved documentation to use a specific registry

- CHANGELOG.md
- brokerapi/brokers/storage/definition.go
fixes #113 by adding two new plans for regional and multi-regional services.
> add regional and multi-regional cloud storage plans

- ci/pipeline.yml
- ci/tasks/build-darwin.yml
- ci/tasks/build-linux.yml
- ci/tasks/build-windows.yml
- ci/tasks/bundle.sh
- ci/tasks/bundle.yml
Create cross-compiled client binaries in our release.
> CI Cross-Compile

- tools/osdfgen/osdfgen.go
needed to also add the build exclusion to the osdfgen.go file
> added build exclusion osdfgen

- brokerapi/brokers/cloudsql/broker_test.go
- pkg/broker/broker_test.go
- pkg/broker/registry_test.go
- pkg/brokerpak/config_test.go
- pkg/toggles/toggle_test.go
Fix flaky tests due to configuration state being persisted across tests.
> Fixing Viper Races

- docs/installation.md
The GCP console flow changed for setting up a project. The documentation was updated accordingly.
> Correct GCP Project Setup

- pkg/providers/tf/wrapper/workspace.go
- utils/retrier.go
- utils/retrier_test.go
This should ~fix~ paper over an issue with CloudSQL and Terraform: https://github.com/terraform-providers/terraform-provider-google/issues/1558.
> added retry to delete

- cmd/client.go
- pkg/brokerpak/cmd.go
- pkg/client/example-runner.go
This PR allows the user to specify which example they want to run.
> add ability to run exactly one example by name

- docs/add-builtin-service.md
> Document how to create a built-in service

- CHANGELOG.md
- OSDF-4.2.3.txt
- docs/customization.md
- docs/use.md
- manifest.yml
- pkg/generator/pcf-artifacts.go
- pkg/providers/builtin/registry_test.go
- pkg/providers/builtin/stackdriver/debugger_definition.go
- pkg/providers/builtin/stackdriver/trace_definition.go
- tile.yml
- utils/version.go
merge back in the release changes
> Release v4.2.3

- pkg/brokerpak/cmd.go
pull in change from develop branch
> generate the brokerpak name based on its version and manifest name

- cmd/serve.go
This command is the same as serve, except it's read only.
> added serve-docs command

- docs/brokerpak-specification.md
- pkg/varcontext/interpolation/eval_test.go
- pkg/varcontext/interpolation/funcs.go
added map flatten function for HIL
This helps map values get structured so Terraform can use them.
> cherrypick #443 to master

- deployments/helm/gcp-service-broker/.gitignore
- deployments/helm/gcp-service-broker/.helmignore
- deployments/helm/gcp-service-broker/Chart.yaml
- deployments/helm/gcp-service-broker/README.md
- deployments/helm/gcp-service-broker/cf-tutorial.md
- deployments/helm/gcp-service-broker/requirements.lock
- deployments/helm/gcp-service-broker/requirements.yaml
- deployments/helm/gcp-service-broker/templates/NOTES.txt
- deployments/helm/gcp-service-broker/templates/_helpers.tpl
- deployments/helm/gcp-service-broker/templates/clusterservicebroker.yaml
- deployments/helm/gcp-service-broker/templates/deployment.yaml
- deployments/helm/gcp-service-broker/templates/ingress.yaml
- deployments/helm/gcp-service-broker/templates/secrets.yaml
- deployments/helm/gcp-service-broker/templates/service.yaml
- deployments/helm/gcp-service-broker/templates/tests/test-connection.yaml
- deployments/helm/gcp-service-broker/values.yaml
> cherrypicked helm

- pkg/broker/broker_test.go
- pkg/broker/service_definition.go
Fixes the broker being unable to read custom plans. Validated locally by running with the following environment variable set and checking that the plans showed up in service listing
```
CLOUDSQL_MYSQL_CUSTOM_PLANS='{"plan-100":{"description":"plan-100","display_name":"plan-100","guid":"495bf186-e1c2-4c7e-abc1-84b1a8634858","max_disk_size":"100","name":"plan-100","pricing_plan":"PER_USE","service":"4bc59b9a-8520-409f-85da-1c7552315863","tier":"db-n1-standard-2"},"custom-plan2":{"description":"test","display_name":"asdf","guid":"938cfc91-bca3-4f9d-b384-1e4ad6f965ce","max_disk_size":"10","name":"custom-plan2","pricing_plan":"PER_USE","service":"4bc59b9a-8520-409f-85da-1c7552315863","tier":"test"}}'
```
> fix reading tile environment

- CHANGELOG.md
- docs/customization.md
- pkg/generator/forms.go
- tile.yml
Made single form fields optional in hopes to fix #549 -- an incompatibility with PAS 2.7.
> made form fields "optional" from the perspective of opsman

- tools/osdfgen/osdfgen.go
- tools/osdfgen/osdfgen_test.go
> support templates in osdfgen
